# Редирект с HTTP на HTTPS
server {
    listen 80;
    server_name whisper.volkov.dev;
    return 301 https://$host$request_uri;
}

# Основной HTTPS сервер
server {
    listen 443 ssl;
    server_name whisper.volkov.dev;

    # Сертификаты Let's Encrypt (будут проброшены с сервера Ubuntu)
    ssl_certificate /etc/letsencrypt/live/whisper.volkov.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/whisper.volkov.dev/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    # Поддержка React Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 8080 ssl;
    server_name whisper.volkov.dev;

    # Сертификаты Let's Encrypt (будут проброшены с сервера Ubuntu)
    ssl_certificate /etc/letsencrypt/live/whisper.volkov.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/whisper.volkov.dev/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    # редирект в контейнер
    location / {
        proxy_pass http://localhost:8081

        # Обязательно переключаем Nginx на HTTP/1.1
        proxy_http_version 1.1;

        # Передаем заголовки для Upgrade соединения
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
}

